# Generated by Django 5.2.1 on 2025-05-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('True', 'مرد'), ('False', 'زن')], default='True', max_length=50, null=True),
        ),
    ]
