# Generated by Django 5.2.1 on 2025-05-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(default='0901', max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
