# Generated by Django 5.2.1 on 2025-07-18 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0012_alter_brand_image_name_alter_product_image_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_type_title', models.CharField(max_length=50, verbose_name='نوع انبار')),
            ],
            options={
                'verbose_name': 'نوع انبار',
                'verbose_name_plural': 'انواع روش انبار',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name='تعداد')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت واحد')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='products.product', verbose_name='کد کالا')),
                ('user_registered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_registered', to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('warehouse_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse', to='warehouses.warehousetype', verbose_name='انبار')),
            ],
            options={
                'verbose_name': 'انبار',
                'verbose_name_plural': 'انبارها',
            },
        ),
    ]
